wip: rust cli
google/glome pull request #185
Opened 2024-10-11 21:01 UTC by burgerdev

First impression of a concise Rust implementation of the CLI - turned out I had this sitting on an abandoned branch.

2024-10-21 08:37 UTC, pkern commented
Generally looks good to me. I have nothing to add to your TODOs. Thanks! :)

2024-10-30 21:41 UTC, burgerdev reviewed
Thanks for the review! I'll leave a couple more TODOs :)

2024-10-30 21:41 UTC, burgerdev commented on rust/Cargo.toml
> +required-features = ["cli"]
Document what this does.

2024-10-30 21:41 UTC, burgerdev commented on rust/src/cli/bin.rs
> +use x25519_dalek::{PublicKey, StaticSecret};
Can we make this crypto-lib-agnostic?

2024-10-30 21:41 UTC, burgerdev commented on rust/src/cli/bin.rs
> +    let _message_tag_suffix = handshake.split_off(33);
Suffix? Prefix?

2024-12-14 17:37 UTC, burgerdev commented on rust/Cargo.toml
> +required-features = ["cli"]
Done

2024-12-14 17:38 UTC, burgerdev commented on rust/src/cli/bin.rs
> +use x25519_dalek::{PublicKey, StaticSecret};
Leaving this open for a future improvement.

2024-12-14 17:38 UTC, burgerdev commented on rust/src/cli/bin.rs
> +    let _message_tag_suffix = handshake.split_off(33);
Renamed

2024-12-15 13:34 UTC, pkern requested changes
Only one typo and a question about errors... Thank you very much, otherwise LGTM

2024-12-15 13:34 UTC, pkern commented on rust/src/cli/bin.rs
> +        .expect("there should be exactly 33 byte in the argument");
bytes

2024-12-15 13:34 UTC, pkern commented on rust/src/cli/bin.rs
> +            return Err("own public key does not match requested prefix".into());
Could we include a debugging hint?

2024-12-21 10:58 UTC, burgerdev commented on rust/src/cli/bin.rs
> +        .expect("there should be exactly 33 byte in the argument");
done

2024-12-21 10:58 UTC, burgerdev commented on rust/src/cli/bin.rs
> +            return Err("own public key does not match requested prefix".into());
done

2024-12-21 19:21 UTC, pkern approved these changes
LGTM.

It'd be good to also have a presubmit GitHub Action, but let's leave that for a followup PR.

2024-12-21 19:21 UTC, merged